name: MystiCore
version: '${project.version}'
main: io.github.mystievous.mysticore.MystiCore
api-version: 1.19
authors: [ Mystievous ]
description: Core library for Mystievous' Plugins
commands:
  custommodel:
    description: Sets the custom model id of your currently held item.
    usage: /custommodel <Model ID>