name: Release Build

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/*.jar
          asset_name: my-project.jar
          asset_content_type: application/java-archive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Upload
        uses: d1ceward/draft-assets-release-action@f2997b18bb04e00260f1d67c796b04a56ca6ea2e
        with:
          files: build/libs/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}